// Corpus regression driver. Two modes:
//   test_corpus <wav_path> <txt_path>                     -- one file, prints result, informational
//   test_corpus --aggregate <corpus_dir> <min_percent>     -- the actual Phase 1 gate
//
// Why aggregate, not per-file 100%: ft8_lib's own unmodified reference demo (built and run
// directly against this corpus to confirm this isn't a bug in argus.c) only recovers 265 of
// 362 expected messages (73%) -- the corpus's ground truth was almost certainly generated by
// WSJT-X, whose decoder is more sophisticated than ft8_lib's. See .claude/state/context.md's
// entry on this. User's call: 70% aggregate recall is the gate for now, individual per-file
// runs stay available for diagnosing a *regression* (a file that used to decode and stopped),
// not for demanding full recall ft8_lib's algorithm can't deliver.
#include <algorithm>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <set>
#include <string>
#include <vector>

extern "C" {
#include "argus.h"
#include <common/wave.h>
}

namespace fs = std::filesystem;

namespace {

std::string trim(const std::string& s)
{
    size_t start = s.find_first_not_of(" \t\r\n");
    if (start == std::string::npos) {
        return "";
    }
    size_t end = s.find_last_not_of(" \t\r\n");
    return s.substr(start, end - start + 1);
}

// Corpus line shape: "HHMMSS SNR DT FREQ ~  MESSAGE_TEXT      trailing annotation". The
// message text itself never contains a run of 2+ spaces (single-space-separated tokens),
// but a trailing DXCC/continent annotation -- when present -- is offset from it by one, so
// splitting on the first run of 2+ spaces after the "~" cleanly separates the two.
std::set<std::string> parse_expected_texts(const std::string& txt_path)
{
    std::set<std::string> texts;
    std::ifstream f(txt_path);
    std::string line;
    while (std::getline(f, line)) {
        size_t tilde = line.find('~');
        if (tilde == std::string::npos) {
            continue;
        }
        std::string rest = trim(line.substr(tilde + 1));
        size_t gap = rest.find("  ");
        std::string message = (gap == std::string::npos) ? rest : trim(rest.substr(0, gap));
        if (!message.empty()) {
            texts.insert(message);
        }
    }
    return texts;
}

std::set<std::string> decode_wav(const std::string& wav_path)
{
    const int kCapacity = 20 * 12000; // 20s @ 12kHz -- comfortably more than one FT8 slot
    std::vector<float> signal(kCapacity);
    int num_samples = kCapacity;
    int sample_rate = 0;
    if (load_wav(signal.data(), &num_samples, &sample_rate, wav_path.c_str()) != 0) {
        std::cerr << "load_wav failed for " << wav_path << "\n";
        return {};
    }

    argus_config_t cfg{};
    cfg.f_min_hz = 200.0f;
    cfg.f_max_hz = 3000.0f;
    cfg.sample_rate_hz = sample_rate;
    cfg.time_osr = 2;
    cfg.freq_osr = 2;

    argus_t argus;
    argus_init(&argus, &cfg);

    int block_size = argus_block_size(&argus);
    for (int pos = 0; pos + block_size <= num_samples; pos += block_size) {
        argus_process_block(&argus, signal.data() + pos);
    }

    argus_decode_t decodes[256];
    int num_decoded = argus_decode_slot(&argus, decodes, 256);
    argus_free(&argus);

    std::set<std::string> actual;
    for (int i = 0; i < num_decoded; ++i) {
        actual.insert(std::string(decodes[i].text));
    }
    return actual;
}

// Evaluates one file, prints a summary line, and returns (expected_count, found_count).
std::pair<size_t, size_t> evaluate_file(const std::string& wav_path, const std::string& txt_path)
{
    std::set<std::string> expected = parse_expected_texts(txt_path);
    std::set<std::string> actual = decode_wav(wav_path);

    size_t found = 0;
    std::vector<std::string> missing;
    for (const auto& e : expected) {
        if (actual.count(e) != 0) {
            ++found;
        } else {
            missing.push_back(e);
        }
    }

    std::cout << wav_path << ": " << found << "/" << expected.size()
              << " expected decodes found (" << actual.size() << " total decoded)\n";
    for (const auto& m : missing) {
        std::cout << "  missing: " << m << "\n";
    }

    return { expected.size(), found };
}

int run_single(const std::string& wav_path, const std::string& txt_path)
{
    auto [expected, found] = evaluate_file(wav_path, txt_path);
    return (found == expected) ? 0 : 1;
}

int run_aggregate(const std::string& corpus_dir, double min_percent)
{
    size_t total_expected = 0;
    size_t total_found = 0;

    std::vector<fs::path> wav_files;
    for (const auto& entry : fs::directory_iterator(corpus_dir)) {
        if (entry.path().extension() == ".wav") {
            wav_files.push_back(entry.path());
        }
    }
    std::sort(wav_files.begin(), wav_files.end());

    for (const auto& wav_path : wav_files) {
        fs::path txt_path = wav_path;
        txt_path.replace_extension(".txt");
        if (!fs::exists(txt_path)) {
            continue;
        }
        auto [expected, found] = evaluate_file(wav_path.string(), txt_path.string());
        total_expected += expected;
        total_found += found;
    }

    double percent = (total_expected == 0) ? 100.0 : (100.0 * (double)total_found / (double)total_expected);
    std::cout << "AGGREGATE: " << total_found << "/" << total_expected << " (" << percent
              << "%), gate is >= " << min_percent << "%\n";
    return (percent >= min_percent) ? 0 : 1;
}

} // namespace

int main(int argc, char** argv)
{
    if (argc == 3) {
        return run_single(argv[1], argv[2]);
    }
    if (argc == 4 && std::string(argv[1]) == "--aggregate") {
        return run_aggregate(argv[2], std::stod(argv[3]));
    }
    std::cerr << "usage: test_corpus <wav_path> <txt_path>\n"
              << "       test_corpus --aggregate <corpus_dir> <min_percent>\n";
    return 2;
}
